➜  relearn-helm git:(main) ✗ kubectl get nodes -o wide
NAME       STATUS   ROLES           AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
minikube   Ready    control-plane   64d   v1.26.3   192.168.49.2   <none>        Ubuntu 20.04.5 LTS   5.15.49-linuxkit   docker://23.0.2
➜  relearn-helm git:(main) ✗ helm version
version.BuildInfo{Version:"v3.11.3", GitCommit:"66a969e7cc08af2377d055f4e6283c33ee84be33", GitTreeState:"clean", GoVersion:"go1.20.3"}
➜  relearn-helm git:(main) ✗



stable helmcharts repo: https://charts.helm.sh/stable/


➜  relearn-helm git:(main) ✗ helm repo add bkstable https://charts.helm.sh/stable
"bkstable" has been added to your repositories
➜  relearn-helm git:(main) ✗ helm search repo bkstable
NAME                                   	CHART VERSION	APP VERSION            	DESCRIPTION
bkstable/acs-engine-autoscaler         	2.2.2        	2.1.1                  	DEPRECATED Scales worker nodes within agent pools
bkstable/aerospike                     	0.3.5        	v4.5.0.5               	DEPRECATED A Helm chart for Aerospike in Kubern...
bkstable/airflow                       	7.13.3       	1.10.12                	DEPRECATED - please use: https://github.com/air...
bkstable/ambassador                    	5.3.2        	0.86.1                 	DEPRECATED A Helm chart for Datawire Ambassador
bkstable/anchore-engine                	1.7.0        	0.7.3                  	Anchore container analysis and policy evaluatio...
bkstable/apm-server                    	2.1.7        	7.0.0                  	DEPRECATED The server receives data from the El...
bkstable/ark                           	4.2.2        	0.10.2                 	DEPRECATED A Helm chart for ark
bkstable/artifactory                   	7.3.2        	6.1.0                  	DEPRECATED Universal Repository Manager support...
bkstable/artifactory-ha                	0.4.2        	6.2.0                  	DEPRECATED Universal Repository Manager support...
bkstable/atlantis                      	3.12.4       	v0.14.0                	DEPRECATED A Helm chart for Atlantis https://ww...
bkstable/auditbeat                     	1.1.2        	6.7.0                  	DEPRECATED A lightweight shipper to audit the a...
bkstable/aws-cluster-autoscaler        	0.3.4        	                       	DEPRECATED Scales worker nodes within autoscali...
bkstable/aws-iam-authenticator         	0.1.5        	1.0                    	DEPRECATED A Helm chart for aws-iam-authenticator
bkstable/bitcoind                      	1.0.2        	0.17.1                 	DEPRECATED Bitcoin is an innovative payment net...
bkstable/bookstack                     	1.2.4        	0.27.5                 	DEPRECATED BookStack is a simple, self-hosted, ...
bkstable/buildkite                     	0.2.4        	3                      	DEPRECATED Agent for Buildkite
bkstable/burrow                        	1.5.4        	0.29.0                 	DEPRECATED Burrow is a permissionable smart con...
bkstable/centrifugo                    	3.2.2        	2.4.0                  	DEPRECATED Centrifugo is a real-time messaging ...
bkstable/cerebro                       	1.9.5        	0.9.2                  	DEPRECATED A Helm chart for Cerebro - a web adm...
bkstable/cert-manager                  	v0.6.7       	v0.6.2                 	A Helm chart for cert-manager
bkstable/chaoskube                     	3.3.2        	0.21.0                 	DEPRECATED Chaoskube periodically kills random ...
bkstable/chartmuseum                   	2.14.2       	0.12.0                 	DEPRECATED Host your own Helm Chart Repository
bkstable/chronograf                    	1.1.1        	1.7.12                 	DEPRECATED Open-source web application written ...
bkstable/clamav                        	1.0.7        	1.6                    	DEPRECATED An Open-Source antivirus engine for ...
bkstable/cloudserver                   	1.0.7        	8.1.5                  	DEPRECATED An open-source Node.js implementatio...
bkstable/cluster-autoscaler            	8.0.0        	1.17.1                 	Scales worker nodes within autoscaling groups.
bkstable/cluster-overprovisioner       	0.4.1        	1.0                    	Installs the a deployment that overprovisions t...
bkstable/cockroachdb                   	3.0.8        	19.2.5                 	DEPRECATED -- CockroachDB is a scalable, surviv...
➜  relearn-helm git:(main) ✗

➜  relearn-helm git:(main) ✗ helm search repo bkstable/acs-engine-autoscaler --versions
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION
bkstable/acs-engine-autoscaler	2.2.2        	2.1.1      	DEPRECATED Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.2.1        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.2.0        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.1.5        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.1.4        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.1.3        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.1.2        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.1.1        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.1.0        	2.1.1      	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	2.0.0        	           	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	1.0.0        	           	Scales worker nodes within agent pools
bkstable/acs-engine-autoscaler	0.1.0        	           	Scales worker nodes within agent pools
➜  relearn-helm git:(main) ✗



➜  relearn-helm git:(main) ✗ helm search repo bkstable/mysql
NAME              	CHART VERSION	APP VERSION	DESCRIPTION
bkstable/mysql    	1.6.9        	5.7.30     	DEPRECATED - Fast, reliable, scalable, and easy...
bkstable/mysqldump	2.6.2        	2.4.1      	DEPRECATED! - A Helm chart to help backup MySQL...
➜  relearn-helm git:(main) ✗ helm search repo bkstable/mysql --versions

